### ISSUE TITLE
Traversal project solution does not contain traversed projects

### ISSUE THREAD

**Issue by ohadschn** [microsoft/slngen#129]
I have the following file at the root of my [repo](https://dev.azure.com/msazure/_git/ADP?version=GBmaster&_a=contents):
```xml
<Project Sdk="Microsoft.Build.Traversal">
  <PropertyGroup>
    <TraversalGlobalProperties>IsTraversal=true</TraversalGlobalProperties>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="src/core/**/*.csproj" />
  </ItemGroup>
</Project>
```

From a VS 2019 (16.5.4) dev CLI I run:
1. `dotnet tool install --global Microsoft.VisualStudio.SlnGen.Tool`
1. `del core.sln && slngen`

Output (I replaced some actual paths on my machine with `XXX`):

> SlnGen version 3.2.2+aca281b938 for .NET Core
> Copyright (c) Microsoft Corporation.  Licensed under the MIT license.
> 
> Build started 20/4/2020 13:37:41.
> Searching "XXX" for projects
> Generating solution for project "XXX\core.proj"
> Loading project references...
> Loaded 39 project(s) in 4,652ms
> Generating Visual Studio solution "XXX\core.sln" ...
> Launching Visual Studio...

The `ProjectReference` pattern in the root traversal project pasted above (`src/core/**/*.csproj`) indeed matches 39 `csproj` files so the logs look good. However the resulting solution file contains only the root traversal project (which VS can't even open): 

```
Microsoft Visual Studio Solution File, Format Version 12.00
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "YYY", "XXX\core.proj", "{76806E8F-D597-4557-B2D1-0BF9349D794A}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {7290F1A9-C282-446D-8011-602F828E1729}
	EndGlobalSection
EndGlobal

```

**Comment by jeffkl** [comment]
By default, SlnGen leaves traversal projects out of the solution since they can't be opened properly in VS.

https://github.com/microsoft/slngen/blob/master/src/Microsoft.VisualStudio.SlnGen/SlnProject.cs#L326

By setting the `TraversalGlobalProperties` value to `IsTraversal=true`, it thinks every project is a traversal project.

The better way do this would be some logic in `Directory.Build.props`:

```xml
<PropertyGroup>
  <IsTraversal Condition="'$(MSBuildProjectFile)' == 'dirs.proj'">true</IsTraversal>
</PropertyGroup>
```

Which [Microsoft.Build.Traversal](https://github.com/microsoft/MSBuildSdks/tree/master/src/Traversal) does automatically if you're using it.
https://github.com/microsoft/MSBuildSdks/blob/master/src/Traversal/Sdk/Sdk.props#L25

**Comment by ohadschn** [comment]
Thanks! very silly of me
