### ISSUE TITLE
No support for wapproj files

### ISSUE THREAD

**Issue by cikuITreti** [microsoft/slngen#211]
Does slngen support wapproj files? When I invoke slngen on a wapproj file I get the following error

![image](https://user-images.githubusercontent.com/1935814/117631308-65fbe480-b17c-11eb-99f0-fe8372864ed1.png)

And from the VS console I get the following error message:

_MyProject.wapproj : error  : The operation could not be completed. Invalid class string_ 

Opening another solution and adding the project manually works, therefore I don't think there is an issue with my project configuration.

Thanks,
Frank.

**Comment by jeffkl** [comment]
SlnGen does not know about `.wapproj` projects yet.  Fortunately, you can tell it what Project Type GUID to use:

https://github.com/microsoft/slngen/blob/main/docs/README.md#custom-project-types

You can also contribute back the project type GUID so that its built in for everyone: https://github.com/microsoft/slngen/blob/main/src/Shared/VisualStudioProjectTypeGuids.cs

**Comment by jeffkl** [comment]
Looks like the project type GUID is `C7167F0D-BC9F-4E6E-AFE1-012C56B48DB5`. [Reference](https://github.com/microsoft/devops-for-windows-apps/blob/master/MyWPFApp.sln#L16)

I'll get this added to the list soon.
