### ISSUE TITLE
SlnGenSolutionItem Include doesn't support wildcard expansion

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/slngen#439]
Seems like I can only include one file per `SlnGenSolutionItem` entry in the `ItemGroup`.

For example, this XML:
```xml
  <ItemGroup>
    <SlnGenSolutionItem Include="$(MSBuildThisFileDirectory).editorconfig" />
    <SlnGenSolutionItem Include="$(MSBuildThisFileDirectory)settings.xamlstyler" />
    <SlnGenSolutionItem Include="$(MSBuildThisFileDirectory)License.md" />
    <SlnGenSolutionItem Include="$(MSBuildThisFileDirectory)ReadMe.md" />
    <SlnGenSolutionItem Include="$(MSBuildThisFileDirectory)common\GlobalUsings.cs" />
    <SlnGenSolutionItem Include="$(MSBuildThisFileDirectory)common\GlobalUsings_Samples.cs" />
    <SlnGenSolutionItem Include="$(MSBuildThisFileDirectory)common\GlobalUsings_Tests.cs" />
    <SlnGenSolutionItem Include="$(MSBuildThisFileDirectory)common\GlobalUsings_WinUI.cs" />
  </ItemGroup>
```

Generates these solution items:

![image](https://user-images.githubusercontent.com/24302614/213312832-5f3e5385-818f-44c6-ad24-7c6a0906a746.png)

However, it'd be nicer to be able to specify ([like other msbuild items allow](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-items?view=vs-2022#use-wildcards-to-specify-items)):

```xml
  <ItemGroup>
    <SlnGenSolutionItem Include="$(MSBuildThisFileDirectory).editorconfig" />
    <SlnGenSolutionItem Include="$(MSBuildThisFileDirectory)settings.xamlstyler" />
    <SlnGenSolutionItem Include="$(MSBuildThisFileDirectory)*.md" />
    <SlnGenSolutionItem Include="$(MSBuildThisFileDirectory)common\GlobalUsings*.cs" />
  </ItemGroup>
```

Would imagine it's this bit of code here:

https://github.com/microsoft/slngen/blob/86a8421625d6bc0bcd31e012ba58d9d63ac5ff58/src/Microsoft.VisualStudio.SlnGen/SlnProject.cs#L343

Is there something that has to be done special to get the expanded glob result?

**Comment by jeffkl** [comment]
At the moment this is a side effect of the MSBuild "feature flag" to disable wildcard expansion in an attempt to make project loading as fast as possible.  SlnGen diables all wildcard expansion except for `*proj` so that other wildcards are left unexpanded so that loading projects can be very fast.  No other items are looked at by SlnGen so it doesn't matter if every single `<Compile Include="**\*.cs" />` item has been expanded.

https://github.com/microsoft/slngen/blob/main/src/Microsoft.VisualStudio.SlnGen/MSBuildFeatureFlags.cs#L102-L112

I think with this off, evaluating a large number of projects takes almost 3 times longer.  But its been a while since I tested it.  Ideally there would be a way to tell MSBuild to only expand wildcards for specific items (`ProjectReference`, `SlnGenSolutionItem`, etc).  

I tested it just now against a repository with 780 projects and SlnGen was **not** any slower with this setting off.  So I'll send a PR to stop setting it.
