### ISSUE TITLE
--collapsefolders = true not working for single sub-folders

### ISSUE THREAD

**Issue by wdcossey** [microsoft/slngen#505]
I have an issue where `--collapsefolders:true` generates a `.sln` file that can't be loaded by Visual Studio (2022), it does work in Rider (just about).

The issue only happens when there's a single folder

```
- root
  - core
    - Project A
      - src
    - Project B
      - src
  - interface
    - Project C
      - src
```

`slngen` will generate the first folder `core` fine but the other `interface` will fail, as it tries to generate a solution folder with an invalid name

Example:
```
Project("{}") = "interface / Project C", "root\interface", "{}"
```

**Comment by michael-hawker** [comment]
Is this the same as #438?

**Comment by glards** [comment]
I experienced the same issue today. After investigating, it seems to be a regression from #495 in v10.2.0. I got around it by downgrading the tool to v10.0.0.

The root cause is that the separator for folder name was changed to '/' which causes Visual Studio to not load the projects under the folders with the following error:

> Solution Folder names cannot:
> - contain any of the following characters: / ? : \ * "" < > |
> - contain Unicode control characters
> - contain surrogate characters
> - be system reserved names, including 'CON', 'AUX', 'PRN', 'COM1' or 'LPT2'
> - be '.' or '..'

The previous code was using character '\u0338'.
